### ISSUE TITLE
web-bundle is wrongly filtered as C# project.

### ISSUE THREAD

**Issue by aloisdg** [iankronquist/y-cloninator#11]
Hello,

[web-bundle](https://github.com/haxorplatform/web-bundle) is filtered as a C# but it should be filtered as JavaScript.

Cheers,

**Comment by tschuy** [comment]
Weird, I wonder how that happened.

I'll pop into the database and fix that but that field is populated directly from the Github API.

**Comment by tschuy** [comment]
I've updated it in the database.

**Comment by aloisdg** [comment]
Nice !
