### ISSUE TITLE
Long text descriptions look awkward

### ISSUE THREAD

**Issue by tschuy** [iankronquist/y-cloninator#13]
> AsyncSSH is a Python package which provides an asynchronous client and server implementation of the SSHv2 protocol on top of the Python asyncio framework. It requires Python 3.4 or later and the Python cryptography library for some cryptographic functions.

Perhaps limit this to two lines as displayable at whatever the current width is? (Is this possible with CSS?)

**Comment by iankronquist** [comment]
fixed by #14
