### ISSUE TITLE
Searching fails on http://ycloninator.herokuapp.com/<language>

### ISSUE THREAD

**Issue by mshenfield** [iankronquist/y-cloninator#7]
Click on a language, causing the page to redirect to http://ycloninator.herokuapp.com/<language>. Try searching, and you'll receive the following error: `Cannot POST /<language`.

**Comment by iankronquist** [comment]
This is fixed on master but @tschuy may not have pushed the latest changes to prod.

**Comment by mshenfield** [comment]
:+1:

**Comment by iankronquist** [comment]
Reopening issue until it's fixed on prod.

**Comment by tschuy** [comment]
#12 has been deployed to prod, so this is fixed.
