### ISSUE TITLE
Handle multiple mentions of a repository on the backend

### ISSUE THREAD

**Issue by mshenfield** [iankronquist/y-cloninator#8]
It would be nice to be able to see how multiple popular posts reference the same repository, and when a repository was first and last mentioned. The schema would be more suited for this task if it switched the relationship of Github Repository to HNPost from 1:1, to 1:many. This would mean moving the `hn_id` and `hn_url` from `ghprojects`, and adding a `gh_url` into `hnposts`. You could either store first and last mentioned, and number of links, or compute it as part of the query when displaying.

**Comment by tschuy** [comment]
Closed by #9, thanks for your PR :smile:
